### ISSUE TITLE
why is log-gamma default shape parameter set to 2.5 rather than 2?

### ISSUE THREAD

**Issue by bbolker** [vdorie/blme#15]
The Chung et al. *Psychometrika* paper discusses a $\textrm{log-gamma}(\alpha = 2, \lambda \to 0)$ setting for the prior (as the least-informative prior that will guarantee variance > 0). Yet the [code](https://github.com/vdorie/blme/blob/2f2d55c26f30fb0e4398aefc74f590c17c75caf6/R/dist.R#L169) uses `shape = 2.5`. Can you say what the justification was? (e.g., does setting the value to exactly 2.0 lead to numeric problems in some cases, and you decided to make it 2.5 rather than [say] 2.001) ?

**Comment by vdorie** [comment]
I really don't remember. It's probably because I wrote the code before the
paper and alpha = 2.5 cancels out the first order bias. I think 2 was used
for the paper because of its linear behavior near 0.
