### ISSUE TITLE
Help! How can I get estimated standard error and confidence interval?

### ISSUE THREAD

**Issue by Simon-Zhen** [vdorie/blme#6]
Hello! I'm a newer to GitHub.
I know this blme package from a paper：
Chung, Y. , Rabe-Hesketh, S. , Dorie, V. , & Andrew Gelman(2013). A nondegenerate penalized likelihood estimator for variance parameters in multilevel models. Psychometrika, 78(4), 685-709.
which suggests that it is helpful to choose a log-gamma penalty(or a weak information prior) for group-level variance.
But I wonder how can I get estimated standard error and confidence interval from this package? (for group-level variance)
Would you please help me? Thanks a lot. 
Best wishes!

**Comment by vdorie** [comment]
Unfortunately, getting confidence intervals for maximum a posteriori estimates isn't straightforward. The idea behind the package is to allow models to be quickly developed/refined when maximum likelihood fails, but to take the result and re-fit it using (much slower) MCMC/full Bayes. For that, you can use something like `MCMCglmm` or `rstanarm`.
